"""Add product_id foreign key to order_items

Revision ID: 20d3ac706498
Revises: b8aa6fa799e1
Create Date: 2025-06-27 01:33:58.201271
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d3ac706498'
down_revision: Union[str, None] = 'b8aa6fa799e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Alter product_id column to change type from VARCHAR to INTEGER, using the 'USING' clause for casting
    op.alter_column('order_items', 'product_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='product_id::integer')  # Added 'USING' clause for type casting
    
    # Add foreign key constraint from product_id in order_items to id in products
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    
    # Drop 'create_account' and 'ship_different' columns from 'orders' table
    op.drop_column('orders', 'create_account')
    op.drop_column('orders', 'ship_different')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add back the 'ship_different' and 'create_account' columns to the 'orders' table
    op.add_column('orders', sa.Column('ship_different', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('create_account', sa.BOOLEAN(), autoincrement=False, nullable=True))
    
    # Drop the foreign key constraint
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    
    # Revert the column type change for 'product_id' from INTEGER back to VARCHAR
    op.alter_column('order_items', 'product_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    
    # ### end Alembic commands ### 
