"""Add is_admin column

Revision ID: c3ca5cce82e8
Revises: 
Create Date: 2025-06-15 19:40:40.896171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3ca5cce82e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_products_id'), table_name='products')
#     op.drop_table('products')
#     op.drop_index(op.f('ix_wishlist_id'), table_name='wishlist')
#     op.drop_table('wishlist')
#     op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
#     # ### end Alembic commands ###

def upgrade() -> None:
    from sqlalchemy import text
    # ✅ Safely add the column with default value
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=text('false')))



def downgrade() -> None:
    # ✅ Clean rollback
    op.drop_column('users', 'is_admin')