"""Add new columns to products table

Revision ID: d9e9a5c2b586
Revises: 554c65c9572b
Create Date: 2025-06-22 02:59:27.250846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9e9a5c2b586'
down_revision: Union[str, None] = '554c65c9572b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('products', sa.Column('total_reviews', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('average_ratings', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('sales_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_deleted')
    op.drop_column('products', 'sales_count')
    op.drop_column('products', 'average_ratings')
    op.drop_column('products', 'total_reviews')
    op.drop_column('products', 'tags')
    op.drop_column('products', 'discount')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'images')
    # ### end Alembic commands ###
