"""Updated Order model

Revision ID: e44cc34a57b7
Revises: 081da1e3d0d3
Create Date: 2025-06-26 16:49:01.239696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44cc34a57b7'
down_revision: Union[str, None] = '081da1e3d0d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'inside_dhaka',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'inside_dhaka',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
